---
# Source: drupal-demo/templates/deployment.yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: ccc-drupal-demo-mariadb
  labels:
    app: ccc-drupal-demo-mariadb-master
    chart: mariadb-5.0.4
    release: "ccc-drupal-demo"
    heritage: "Tiller"
type: Opaque
data:

  mariadb-root-password: "cGFzc3cwcmQ="
  mariadb-password: "cGFzc3cwcmQ="
  mariadb-replication-password: "cGFzc3cwcmQ="
---
apiVersion: v1
kind: Secret
metadata:
  name: ccc-drupal-demo-drupal
  labels:
    app: ccc-drupal-demo-drupal
    chart: drupal-2.1.0
    release: "ccc-drupal-demo"
    heritage: "Tiller"
type: Opaque
data:

  drupal-password: "YWRtaW4="
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ccc-drupal-demo-mariadb-master-init-scripts
  labels:
    app: ccc-drupal-demo-mariadb-master
    component: "master"
    chart: mariadb-5.0.4
    release: "ccc-drupal-demo"
    heritage: "Tiller"
data:
  README.md: |-
    You can copy here your custom .sh, .sql or .sql.gz file so they are executed during the first boot of the image.

    More info in the [bitnami-docker-mariadb](https://github.com/bitnami/bitnami-docker-mariadb#initializing-a-new-instance) repository.
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ccc-drupal-demo-mariadb-master
  labels:
    app: ccc-drupal-demo-mariadb-master
    component: "master"
    chart: mariadb-5.0.4
    release: "ccc-drupal-demo"
    heritage: "Tiller"
data:
  my.cnf: |-
    [mysqld]
    skip-name-resolve
    explicit_defaults_for_timestamp
    basedir=/opt/bitnami/mariadb
    port=3306
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    tmpdir=/opt/bitnami/mariadb/tmp
    max_allowed_packet=16M
    bind-address=0.0.0.0
    pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
    log-error=/opt/bitnami/mariadb/logs/mysqld.log
    character-set-server=UTF8
    collation-server=utf8_general_ci

    [client]
    port=3306
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    default-character-set=UTF8

    [manager]
    port=3306
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ccc-drupal-demo-mariadb-slave
  labels:
    app: ccc-drupal-demo-mariadb-slave
    component: "slave"
    chart: mariadb-5.0.4
    release: "ccc-drupal-demo"
    heritage: "Tiller"
data:
  my.cnf: |-
    [mysqld]
    skip-name-resolve
    explicit_defaults_for_timestamp
    basedir=/opt/bitnami/mariadb
    port=3306
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    tmpdir=/opt/bitnami/mariadb/tmp
    max_allowed_packet=16M
    bind-address=0.0.0.0
    pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
    log-error=/opt/bitnami/mariadb/logs/mysqld.log
    character-set-server=UTF8
    collation-server=utf8_general_ci

    [client]
    port=3306
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    default-character-set=UTF8

    [manager]
    port=3306
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ccc-drupal-demo-mariadb-tests
data:
  run.sh: |-
    @test "Testing MariaDB is accessible" {
      mysql -h ccc-drupal-demo-mariadb -uroot -p$MARIADB_ROOT_PASSWORD -e 'show databases;'
    }
---
apiVersion: v1
kind: Service
metadata:
  name: ccc-drupal-demo-mariadb-master
  labels:
    app: ccc-drupal-demo-mariadb-master
    component: "master"
    chart: mariadb-5.0.4
    release: "ccc-drupal-demo"
    heritage: "Tiller"
spec:
  type: ClusterIP
  ports:
  - name: mysql
    port: 3306
    targetPort: mysql
  selector:
    app: ccc-drupal-demo-mariadb-master
    component: "master"
    release: "ccc-drupal-demo"
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ccc-drupal-demo-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: ccc.demo.ibm.com
    http:
      paths:
      - backend:
          serviceName: ccc-drupal-demo-drupal
          servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ccc-drupal-demo-mariadb-slave
  labels:
    app: ccc-drupal-demo-mariadb-slave
    chart: mariadb-5.0.4
    component: "slave"
    release: "ccc-drupal-demo"
    heritage: "Tiller"
spec:
  type: ClusterIP
  ports:
  - name: mysql
    port: 3306
    targetPort: mysql
  selector:
    app: ccc-drupal-demo-mariadb-slave
    component: "slave"
    release: "ccc-drupal-demo"
---
apiVersion: v1
kind: Service
metadata:
  name: ccc-drupal-demo-drupal
  labels:
    app: ccc-drupal-demo-drupal
    chart: drupal-2.1.0
    release: "ccc-drupal-demo"
    heritage: "Tiller"
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: https
    port: 443
    targetPort: https
  selector:
    app: ccc-drupal-demo-drupal
---
apiVersion: v1
kind: Pod
metadata:
  name: "ccc-drupal-demo-mariadb-test-aovqc"
  annotations:
    "helm.sh/hook": test-success
spec:
  initContainers:
    - name: "test-framework"
      image: "dduportal/bats:0.4.0"
      command:
        - "bash"
        - "-c"
        - |
          set -ex
          # copy bats to tools dir
          cp -R /usr/local/libexec/ /tools/bats/
      volumeMounts:
      - mountPath: /tools
        name: tools
  containers:
    - name: mariadb-test
      image: "docker.io/bitnami/mariadb:10.1.36-debian-9"
      imagePullPolicy: "IfNotPresent"
      command: ["/tools/bats/bats", "-t", "/tests/run.sh"]
      env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ccc-drupal-demo-mariadb
              key: mariadb-root-password
      volumeMounts:
      - mountPath: /tests
        name: tests
        readOnly: true
      - mountPath: /tools
        name: tools
  volumes:
  - name: tests
    configMap:
      name: ccc-drupal-demo-mariadb-tests
  - name: tools
    emptyDir: {}
  restartPolicy: Never
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ccc-drupal-demo-drupal
  labels:
    app: ccc-drupal-demo-drupal
    chart: drupal-2.1.0
    release: "ccc-drupal-demo"
    heritage: "Tiller"
spec:
  selector:
    matchLabels:
      app: ccc-drupal-demo-drupal
      release: "ccc-drupal-demo"
  replicas: 1
  template:
    metadata:
      labels:
        app: ccc-drupal-demo-drupal
        chart: drupal-2.1.0
        release: "ccc-drupal-demo"
    spec:
      containers:
      - name: ccc-drupal-demo-drupal
        image: "docker.io/bitnami/drupal:8.6.1-debian-9"
        imagePullPolicy: "IfNotPresent"
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        - name: MARIADB_HOST
          value: ccc-drupal-demo-mariadb-master
        - name: MARIADB_PORT_NUMBER
          value: "3306"
        - name: DRUPAL_DATABASE_NAME
          value: "drupal-ccc"
        - name: DRUPAL_DATABASE_USER
          value: "db_user"
        - name: DRUPAL_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ccc-drupal-demo-mariadb
              key: mariadb-password
        - name: DRUPAL_PROFILE
          value: "standard"
        - name: DRUPAL_USERNAME
          value: "admin"
        - name: DRUPAL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ccc-drupal-demo-drupal
              key: drupal-password
        - name: DRUPAL_EMAIL
          value: "user@example.com"
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        livenessProbe:
          httpGet:
            path: /user/login
            port: http
          initialDelaySeconds: 240

        readinessProbe:
          httpGet:
            path: /user/login
            port: http
          initialDelaySeconds: 30

        resources:
          requests:
            cpu: 300m
            memory: 512Mi

        volumeMounts:
        - name: drupal-data
          mountPath: /bitnami/drupal
        - name: apache-data
          mountPath: /bitnami/apache
      volumes:
      - name: drupal-data
        emptyDir: {}
      - name: apache-data
        emptyDir: {}
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: ccc-drupal-demo-mariadb-master
  labels:
    app: ccc-drupal-demo-mariadb-master
    chart: mariadb-5.0.4
    component: "master"
    release: "ccc-drupal-demo"
    heritage: "Tiller"
spec:
  selector:
    matchLabels:
      release: "ccc-drupal-demo"
      component: "master"
      app: ccc-drupal-demo-mariadb-master
  serviceName: "ccc-drupal-demo-mariadb-master"
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ccc-drupal-demo-mariadb-master
        component: "master"
        release: "ccc-drupal-demo"
        chart: mariadb-5.0.4
    spec:
      securityContext:
        runAsUser: 1001
        fsGroup: 1001
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app: ccc-drupal-demo-mariadb-master
                  release: "ccc-drupal-demo"
      containers:
      - name: "mariadb"
        image: "docker.io/bitnami/mariadb:10.1.36-debian-9"
        imagePullPolicy: "IfNotPresent"
        env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ccc-drupal-demo-mariadb
              key: mariadb-root-password
        - name: MARIADB_USER
          value: "db_user"
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ccc-drupal-demo-mariadb
              key: mariadb-password
        - name: MARIADB_DATABASE
          value: "drupal-ccc"
        - name: MARIADB_REPLICATION_MODE
          value: "master"
        - name: MARIADB_REPLICATION_USER
          value: "replicator"
        - name: MARIADB_REPLICATION_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ccc-drupal-demo-mariadb
              key: mariadb-replication-password
        ports:
        - name: mysql
          containerPort: 3306
        livenessProbe:
          exec:
            command: ["sh", "-c", "exec mysqladmin status -uroot -p$MARIADB_ROOT_PASSWORD"]
          initialDelaySeconds: 240
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          exec:
            command: ["sh", "-c", "exec mysqladmin status -uroot -p$MARIADB_ROOT_PASSWORD"]
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        resources:
          {}

        volumeMounts:
        - name: data
          mountPath: /bitnami/mariadb
        - name: custom-init-scripts
          mountPath: /docker-entrypoint-initdb.d
        - name: config
          mountPath: /opt/bitnami/mariadb/conf/my.cnf
          subPath: my.cnf
      volumes:
        - name: config
          configMap:
            name: ccc-drupal-demo-mariadb-master
        - name: custom-init-scripts
          configMap:
            name: ccc-drupal-demo-mariadb-master-init-scripts
        - name: "data"
          emptyDir: {}
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: ccc-drupal-demo-mariadb-slave
  labels:
    app: ccc-drupal-demo-mariadb-slave
    chart: mariadb-5.0.4
    component: "slave"
    release: "ccc-drupal-demo"
    heritage: "Tiller"
spec:
  selector:
    matchLabels:
      release: "ccc-drupal-demo"
      component: "slave"
      app: ccc-drupal-demo-mariadb-slave
  serviceName: "ccc-drupal-demo-mariadb-slave"
  replicas: 2
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ccc-drupal-demo-mariadb-slave
        component: "slave"
        release: "ccc-drupal-demo"
        chart: mariadb-5.0.4
    spec:
      securityContext:
        runAsUser: 1001
        fsGroup: 1001
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app: ccc-drupal-demo-mariadb-slave
                  release: "ccc-drupal-demo"
      containers:
      - name: "mariadb"
        image: "docker.io/bitnami/mariadb:10.1.36-debian-9"
        imagePullPolicy: "IfNotPresent"
        env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ccc-drupal-demo-mariadb
              key: mariadb-root-password
        - name: MARIADB_USER
          value: "db_user"
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ccc-drupal-demo-mariadb
              key: mariadb-password
        - name: MARIADB_DATABASE
          value: "drupal-ccc"
        - name: MARIADB_REPLICATION_MODE
          value: "slave"
        - name: MARIADB_MASTER_HOST
          value: ccc-drupal-demo-mariadb
        - name: MARIADB_MASTER_PORT_NUMBER
          value: "3306"
        - name: MARIADB_MASTER_ROOT_USER
          value: "root"
        - name: MARIADB_MASTER_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ccc-drupal-demo-mariadb
              key: mariadb-root-password
        - name: MARIADB_REPLICATION_USER
          value: "replicator"
        - name: MARIADB_REPLICATION_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ccc-drupal-demo-mariadb
              key: mariadb-replication-password
        ports:
        - name: mysql
          containerPort: 3306
        livenessProbe:
          exec:
            command: ["sh", "-c", "exec mysqladmin status -uroot -p$MARIADB_ROOT_PASSWORD"]
          initialDelaySeconds: 240
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          exec:
            command: ["sh", "-c", "exec mysqladmin status -uroot -p$MARIADB_ROOT_PASSWORD"]
          initialDelaySeconds: 45
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        resources:
          {}

        volumeMounts:
        - name: data
          mountPath: /bitnami/mariadb
        - name: config
          mountPath: /opt/bitnami/mariadb/conf/my.cnf
          subPath: my.cnf
      volumes:
        - name: config
          configMap:
            name: ccc-drupal-demo-mariadb-slave
        - name: "data"
          emptyDir: {}

---
# Source: drupal-demo/templates/calico.yaml

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ccc-drupal-demo-calico
spec:
  podSelector:
    matchLabels:
      app: ccc-drupal-demo-mariadb-master
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: ccc-drupal-demo-drupal
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ccc-drupal-demo-calico-ingress
  namespace: dev-namespace
spec:
  podSelector:
    matchLabels:
      app: ccc-drupal-demo-drupal
  ingress:
    - from:
      - namespaceSelector:
          matchLabels: {}

