---
# Source: drupal-demo/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: drupalxxx-drupal-demo
  labels:
    app: drupalxxx-drupal-demo
    chart: drupal-demo-3.1.0
    release: "drupalxxx"
    heritage: "Tiller"
type: Opaque
data:
  
  drupal-password: "YWRtaW4="
  

---
# Source: drupal-demo/templates/apache-pvc.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: drupalxxx-drupal-demo-apache
  labels:
    app: drupalxxx-drupal-demo
    chart: drupal-demo-3.1.0
    release: "drupalxxx"
    heritage: "Tiller"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
---
# Source: drupal-demo/templates/drupal-pvc.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: drupalxxx-drupal-demo-drupal
  labels:
    app: drupalxxx-drupal-demo
    chart: drupal-demo-3.1.0
    release: "drupalxxx"
    heritage: "Tiller"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "8Gi"
---
# Source: drupal-demo/templates/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: drupalxxx-drupal-demo
  labels:
    app: drupalxxx-drupal-demo
    chart: drupal-demo-3.1.0
    release: "drupalxxx"
    heritage: "Tiller"
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: https
    port: 443
    targetPort: https
  selector:
    app: drupalxxx-drupal-demo

---
# Source: drupal-demo/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: drupalxxx-drupal-demo
  labels:
    app: drupalxxx-drupal-demo
    chart: drupal-demo-3.1.0
    release: "drupalxxx"
    heritage: "Tiller"
spec:
  selector:
    matchLabels:
      app: drupalxxx-drupal-demo
      release: "drupalxxx"
  replicas: 1
  template:
    metadata:
      labels:
        app: drupalxxx-drupal-demo
        chart: drupal-demo-3.1.0
        release: "drupalxxx"
    spec:
      containers:
      - name: drupalxxx-drupal-demo
        image: "docker.io/bitnami/drupal:8.6.1-debian-9"
        imagePullPolicy: "IfNotPresent"
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        - name: MARIADB_HOST
          value: drupalxxx-drupal-demo.dev-namespacde.svc.cluster.local:3306
        - name: MARIADB_PORT_NUMBER
          value: "3306"
        - name: DRUPAL_DATABASE_NAME
          value: "drupalxxx"
        - name: DRUPAL_DATABASE_USER
          value: "drupal"
        - name: DRUPAL_DATABASE_PASSWORD
          value: "drupal"
        - name: DRUPAL_PROFILE
          value: "standard"
        - name: DRUPAL_USERNAME
          value: "admin"
        - name: DRUPAL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: drupalxxx-drupal-demo
              key: drupal-password
        - name: DRUPAL_EMAIL
          value: "user@example.com"
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        livenessProbe:
          httpGet:
            path: /user/login
            port: http
          initialDelaySeconds: 120
          
        readinessProbe:
          httpGet:
            path: /user/login
            port: http
          initialDelaySeconds: 30
          
        resources:
          requests:
            cpu: 300m
            memory: 512Mi
          
        volumeMounts:
        - name: drupal-data
          mountPath: /bitnami/drupal
        - name: apache-data
          mountPath: /bitnami/apache
      volumes:
      - name: drupal-data
        persistentVolumeClaim:
          claimName: drupalxxx-drupal-demo-drupal
      - name: apache-data
        persistentVolumeClaim:
          claimName: drupalxxx-drupal-demo-apache

---
# Source: drupal-demo/templates/drupal-pv.yaml

---
# Source: drupal-demo/templates/ingress.yaml


