apiVersion: v1
entries:
  drupal-demo:
  - appVersion: 8.6.1
    created: 2018-10-17T15:01:03.84082578+02:00
    description: A demo for Drupal on IBM private or public cloud
    digest: b5a9de4602974691eac10b44a6382ab200e80a27ca243224c022e76325f1c30b
    engine: gotpl
    home: http://www.drupal.org/
    icon: https://raw.githubusercontent.com/niklaushirt/drupaldemo/master/helm/charts/icons/icp.png
    keywords:
    - drupal
    - cms
    - blog
    - http
    - web
    - application
    - php
    - runtime
    maintainers:
    - email: nikh@ch.ibm.com
      name: Niklaus Hirt
    name: drupal-demo
    sources:
    - https://github.com/bitnami/bitnami-docker-drupal
    urls:
    - https://raw.githubusercontent.com/niklaushirt/drupaldemo/master/helm/charts/repo/stable/drupal-demo-3.1.8.tgz
    version: 3.1.8
  - appVersion: 8.6.1
    created: 2018-10-17T15:01:03.839609477+02:00
    description: A demo for Drupal on IBM private or public cloud
    digest: b675948985e259a4b94b7c65a2bae2143e7858f460d9b6ee78d678d7f165d5a6
    engine: gotpl
    home: http://www.drupal.org/
    icon: https://raw.githubusercontent.com/niklaushirt/drupaldemo/master/helm/charts/icons/icp.png
    keywords:
    - drupal
    - cms
    - blog
    - http
    - web
    - application
    - php
    - runtime
    maintainers:
    - email: nikh@ch.ibm.com
      name: Niklaus Hirt
    name: drupal-demo
    sources:
    - https://github.com/bitnami/bitnami-docker-drupal
    urls:
    - https://raw.githubusercontent.com/niklaushirt/drupaldemo/master/helm/charts/repo/stable/drupal-demo-3.1.7.tgz
    version: 3.1.7
  - appVersion: 8.6.1
    created: 2018-10-17T15:01:03.837622893+02:00
    description: A demo for Drupal on IBM private or public cloud
    digest: acafba6f636fa1771a04ffe6bf37ffc149e5fcbaedd4807676f1bc6b310fd63c
    engine: gotpl
    home: http://www.drupal.org/
    icon: https://raw.githubusercontent.com/niklaushirt/drupaldemo/master/helm/charts/icons/icp.png
    keywords:
    - drupal
    - cms
    - blog
    - http
    - web
    - application
    - php
    - runtime
    maintainers:
    - email: nikh@ch.ibm.com
      name: Niklaus Hirt
    name: drupal-demo
    sources:
    - https://github.com/bitnami/bitnami-docker-drupal
    urls:
    - https://raw.githubusercontent.com/niklaushirt/drupaldemo/master/helm/charts/repo/stable/drupal-demo-3.1.6.tgz
    version: 3.1.6
generated: 2018-10-17T15:01:03.835251293+02:00
