apiVersion: v1
entries:
  drupal-demo:
  - appVersion: 8.6.1
    created: 2018-10-17T10:30:35.72064173+02:00
    description: A demo for Drupal on IBM private or public cloud
    digest: 58531d521a06f23096650292fd06eec3f012f1495392e4b25218ba46bc123a34
    engine: gotpl
    home: http://www.drupal.org/
    icon: https://raw.githubusercontent.com/niklaushirt/drupaldemo/master/helm/charts/icons/icp.png
    keywords:
    - drupal
    - cms
    - blog
    - http
    - web
    - application
    - php
    - runtime
    maintainers:
    - email: nikh@ch.ibm.com
      name: Niklaus Hirt
    name: drupal-demo
    sources:
    - https://github.com/bitnami/bitnami-docker-drupal
    urls:
    - https://raw.githubusercontent.com/niklaushirt/drupaldemo/master/helm/charts/repo/stable/drupal-demo-3.1.6.tgz
    version: 3.1.6
generated: 2018-10-17T10:30:35.718929563+02:00
