name: drupal-demo
version: 1.0.0
appVersion: 8.6.1
description: A demo for Drupal on IBM private or public cloud
keywords:
- drupal
- cms
- blog
- http
- web
- application
- php
- runtimes
home: http://www.drupal.org/
icon: https://github.com/niklaushirt/drupaldemo/blob/master/helm/charts/icons/icp.png
sources:
- https://github.com/bitnami/bitnami-docker-drupal
maintainers:
- name: Niklaus Hirt
  email: nikh@ch.ibm.com
engine: gotpl
