{
 "title": "ICP Drupal Performance",
 "description": "Monitors Kubernetes cluster using Prometheus. Shows overall cluster CPU / Memory / Filesystem usage as well as individual pod, containers, systemd services statistics. Uses cAdvisor metrics only.",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "interval",
    "query": "30s,1m,2m,3m,5m,7m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "namespace", "label": "Namespace", "query": "label_values(namespace)" }
  ]
 },
 "panels": [
  {
   "title": "Namespace \"$namespace\"  CPU by pod name",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod_name=~\".*drupal.*\", namespace=\"$namespace\"}[$interval])) by (pod_name) * 100",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Namespace  \"$namespace\"  Memory by pod name",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " sort_desc(sum(container_memory_usage_bytes{image!=\"\", namespace=\"$namespace\", pod_name=~\".*drupal.*\"}) by (pod_name, image))",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "$namespace kube_pod_container_status_ready",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "kube_pod_container_status_ready{container=~\".*drupal.*\", namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}