---
# Source: drupal/charts/mariadb/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: cool-mariadb
  labels:
    app: "mariadb"
    chart: mariadb-5.0.4
    release: "cool"
    heritage: "Tiller"
type: Opaque
data:
  mariadb-root-password: "dGIwUG1hM2h2cQ=="
  
  mariadb-password: "NnpBcjJ3QWhnRg=="
  mariadb-replication-password: "ellweXNFejFDOQ=="
---
# Source: drupal/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: cool-drupal
  labels:
    app: cool-drupal
    chart: drupal-2.1.0
    release: "cool"
    heritage: "Tiller"
type: Opaque
data:
  
  drupal-password: "YWRtaW4="
  

---
# Source: drupal/charts/mariadb/templates/initialization-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: cool-mariadb-master-init-scripts
  labels:
    app: mariadb
    component: "master"
    chart: mariadb-5.0.4
    release: "cool"
    heritage: "Tiller"
data:
  README.md: |-
    You can copy here your custom .sh, .sql or .sql.gz file so they are executed during the first boot of the image.
  
    More info in the [bitnami-docker-mariadb](https://github.com/bitnami/bitnami-docker-mariadb#initializing-a-new-instance) repository.
  

---
# Source: drupal/charts/mariadb/templates/master-configmap.yaml

apiVersion: v1
kind: ConfigMap
metadata:
  name: cool-mariadb-master
  labels:
    app: mariadb
    component: "master"
    chart: mariadb-5.0.4
    release: "cool"
    heritage: "Tiller"
data:
  my.cnf: |-
    [mysqld]
    skip-name-resolve
    explicit_defaults_for_timestamp
    basedir=/opt/bitnami/mariadb
    port=3306
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    tmpdir=/opt/bitnami/mariadb/tmp
    max_allowed_packet=16M
    bind-address=0.0.0.0
    pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
    log-error=/opt/bitnami/mariadb/logs/mysqld.log
    character-set-server=UTF8
    collation-server=utf8_general_ci
    
    [client]
    port=3306
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    default-character-set=UTF8
    
    [manager]
    port=3306
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
---
# Source: drupal/charts/mariadb/templates/slave-configmap.yaml

apiVersion: v1
kind: ConfigMap
metadata:
  name: cool-mariadb-slave
  labels:
    app: mariadb
    component: "slave"
    chart: mariadb-5.0.4
    release: "cool"
    heritage: "Tiller"
data:
  my.cnf: |-
    [mysqld]
    skip-name-resolve
    explicit_defaults_for_timestamp
    basedir=/opt/bitnami/mariadb
    port=3306
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    tmpdir=/opt/bitnami/mariadb/tmp
    max_allowed_packet=16M
    bind-address=0.0.0.0
    pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
    log-error=/opt/bitnami/mariadb/logs/mysqld.log
    character-set-server=UTF8
    collation-server=utf8_general_ci
    
    [client]
    port=3306
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    default-character-set=UTF8
    
    [manager]
    port=3306
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid

---
# Source: drupal/charts/mariadb/templates/tests.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: cool-mariadb-tests
data:
  run.sh: |-
    @test "Testing MariaDB is accessible" {
      mysql -h cool-mariadb -uroot -p$MARIADB_ROOT_PASSWORD -e 'show databases;'
    }

---
# Source: drupal/charts/mariadb/templates/master-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: cool-mariadb
  labels:
    app: "mariadb"
    component: "master"
    chart: mariadb-5.0.4
    release: "cool"
    heritage: "Tiller"
spec:
  type: ClusterIP
  ports:
  - name: mysql
    port: 3306
    targetPort: mysql
  selector:
    app: "mariadb"
    component: "master"
    release: "cool"

---
# Source: drupal/charts/mariadb/templates/slave-svc.yaml

apiVersion: v1
kind: Service
metadata:
  name: cool-mariadb-slave
  labels:
    app: "mariadb"
    chart: mariadb-5.0.4
    component: "slave"
    release: "cool"
    heritage: "Tiller"
spec:
  type: ClusterIP
  ports:
  - name: mysql
    port: 3306
    targetPort: mysql
  selector:
    app: "mariadb"
    component: "slave"
    release: "cool"

---
# Source: drupal/templates/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: cool-drupal
  labels:
    app: cool-drupal
    chart: drupal-2.1.0
    release: "cool"
    heritage: "Tiller"
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: https
    port: 443
    targetPort: https
  selector:
    app: cool-drupal

---
# Source: drupal/charts/mariadb/templates/test-runner.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "cool-mariadb-test-eiajc"
  annotations:
    "helm.sh/hook": test-success
spec:
  initContainers:
    - name: "test-framework"
      image: "dduportal/bats:0.4.0"
      command:
        - "bash"
        - "-c"
        - |
          set -ex
          # copy bats to tools dir
          cp -R /usr/local/libexec/ /tools/bats/
      volumeMounts:
      - mountPath: /tools
        name: tools
  containers:
    - name: mariadb-test
      image: "docker.io/bitnami/mariadb:10.1.36-debian-9"
      imagePullPolicy: "IfNotPresent"
      command: ["/tools/bats/bats", "-t", "/tests/run.sh"]
      env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cool-mariadb
              key: mariadb-root-password
      volumeMounts:
      - mountPath: /tests
        name: tests
        readOnly: true
      - mountPath: /tools
        name: tools
  volumes:
  - name: tests
    configMap:
      name: cool-mariadb-tests
  - name: tools
    emptyDir: {}
  restartPolicy: Never

---
# Source: drupal/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cool-drupal
  labels:
    app: cool-drupal
    chart: drupal-2.1.0
    release: "cool"
    heritage: "Tiller"
spec:
  selector:
    matchLabels:
      app: cool-drupal
      release: "cool"
  replicas: 1
  template:
    metadata:
      labels:
        app: cool-drupal
        chart: drupal-2.1.0
        release: "cool"
    spec:
      containers:
      - name: cool-drupal
        image: "docker.io/bitnami/drupal:8.6.1-debian-9"
        imagePullPolicy: "IfNotPresent"
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        - name: MARIADB_HOST
          value: cool-mariadb
        - name: MARIADB_PORT_NUMBER
          value: "3306"
        - name: DRUPAL_DATABASE_NAME
          value: "bitnami_drupal"
        - name: DRUPAL_DATABASE_USER
          value: "bn_drupal"
        - name: DRUPAL_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cool-mariadb
              key: mariadb-password
        - name: DRUPAL_PROFILE
          value: "standard"
        - name: DRUPAL_USERNAME
          value: "admin"
        - name: DRUPAL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cool-drupal
              key: drupal-password
        - name: DRUPAL_EMAIL
          value: "user@example.com"
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        livenessProbe:
          httpGet:
            path: /user/login
            port: http
          initialDelaySeconds: 120
          
        readinessProbe:
          httpGet:
            path: /user/login
            port: http
          initialDelaySeconds: 30
          
        resources:
          requests:
            cpu: 300m
            memory: 512Mi
          
        volumeMounts:
        - name: drupal-data
          mountPath: /bitnami/drupal
        - name: apache-data
          mountPath: /bitnami/apache
      volumes:
      - name: drupal-data
        emptyDir: {}
      - name: apache-data
        emptyDir: {}

---
# Source: drupal/charts/mariadb/templates/master-statefulset.yaml
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: cool-mariadb-master
  labels:
    app: "mariadb"
    chart: mariadb-5.0.4
    component: "master"
    release: "cool"
    heritage: "Tiller"
spec:
  selector:
    matchLabels:
      release: "cool"
      component: "master"
      app: mariadb
  serviceName: "cool-mariadb-master"
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: "mariadb"
        component: "master"
        release: "cool"
        chart: mariadb-5.0.4
    spec:
      securityContext:
        runAsUser: 1001
        fsGroup: 1001
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app: "mariadb"
                  release: "cool"
      containers:
      - name: "mariadb"
        image: docker.io/bitnami/mariadb:10.1.36-debian-9
        imagePullPolicy: "IfNotPresent"
        env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cool-mariadb
              key: mariadb-root-password
        - name: MARIADB_USER
          value: "bn_drupal"
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cool-mariadb
              key: mariadb-password
        - name: MARIADB_DATABASE
          value: "bitnami_drupal"
        - name: MARIADB_REPLICATION_MODE
          value: "master"
        - name: MARIADB_REPLICATION_USER
          value: "replicator"
        - name: MARIADB_REPLICATION_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cool-mariadb
              key: mariadb-replication-password
        ports:
        - name: mysql
          containerPort: 3306
        livenessProbe:
          exec:
            command: ["sh", "-c", "exec mysqladmin status -uroot -p$MARIADB_ROOT_PASSWORD"]
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          exec:
            command: ["sh", "-c", "exec mysqladmin status -uroot -p$MARIADB_ROOT_PASSWORD"]
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        resources:
          {}
          
        volumeMounts:
        - name: data
          mountPath: /bitnami/mariadb
        - name: custom-init-scripts
          mountPath: /docker-entrypoint-initdb.d
        - name: config
          mountPath: /opt/bitnami/mariadb/conf/my.cnf
          subPath: my.cnf
      volumes:
        - name: config
          configMap:
            name: cool-mariadb-master
        - name: custom-init-scripts
          configMap:
            name: cool-mariadb-master-init-scripts
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          app: "mariadb"
          chart: mariadb-5.0.4
          component: "master"
          release: "cool"
          heritage: "Tiller"
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "8Gi"

---
# Source: drupal/charts/mariadb/templates/slave-statefulset.yaml

apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: cool-mariadb-slave
  labels:
    app: "mariadb"
    chart: mariadb-5.0.4
    component: "slave"
    release: "cool"
    heritage: "Tiller"
spec:
  selector:
    matchLabels:
      release: "cool"
      component: "slave"
      app: mariadb
  serviceName: "cool-mariadb-slave"
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: "mariadb"
        component: "slave"
        release: "cool"
        chart: mariadb-5.0.4
    spec:
      securityContext:
        runAsUser: 1001
        fsGroup: 1001
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app: "mariadb"
                  release: "cool"
      containers:
      - name: "mariadb"
        image: docker.io/bitnami/mariadb:10.1.36-debian-9
        imagePullPolicy: "IfNotPresent"
        env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cool-mariadb
              key: mariadb-root-password
        - name: MARIADB_USER
          value: "bn_drupal"
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cool-mariadb
              key: mariadb-password
        - name: MARIADB_DATABASE
          value: "bitnami_drupal"
        - name: MARIADB_REPLICATION_MODE
          value: "slave"
        - name: MARIADB_MASTER_HOST
          value: cool-mariadb
        - name: MARIADB_MASTER_PORT_NUMBER
          value: "3306"
        - name: MARIADB_MASTER_ROOT_USER
          value: "root"
        - name: MARIADB_MASTER_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cool-mariadb
              key: mariadb-root-password
        - name: MARIADB_REPLICATION_USER
          value: "replicator"
        - name: MARIADB_REPLICATION_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cool-mariadb
              key: mariadb-replication-password
        ports:
        - name: mysql
          containerPort: 3306
        livenessProbe:
          exec:
            command: ["sh", "-c", "exec mysqladmin status -uroot -p$MARIADB_ROOT_PASSWORD"]
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          exec:
            command: ["sh", "-c", "exec mysqladmin status -uroot -p$MARIADB_ROOT_PASSWORD"]
          initialDelaySeconds: 45
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        resources:
          {}
          
        volumeMounts:
        - name: data
          mountPath: /bitnami/mariadb
        - name: config
          mountPath: /opt/bitnami/mariadb/conf/my.cnf
          subPath: my.cnf
      volumes:
        - name: config
          configMap:
            name: cool-mariadb-slave
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          app: "mariadb"
          chart: mariadb-5.0.4
          component: "slave"
          release: "cool"
          heritage: "Tiller"
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "8Gi"

---
# Source: drupal/templates/apache-pvc.yaml

---
# Source: drupal/templates/drupal-pv.yaml

---
# Source: drupal/templates/drupal-pvc.yaml

---
# Source: drupal/templates/ingress.yaml




