{{- if .Values.web.ingress.security }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "drupal.fullname" . }}-calico
spec:
  podSelector:
    matchLabels:
      app: {{ template "drupal.fullname" . }}-mariadb-master
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: {{ template "drupal.fullname" . }}-drupal
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "drupal.fullname" . }}-calico-m-s
spec:
  podSelector:
    matchLabels:
      app: {{ template "drupal.fullname" . }}-mariadb-master
  ingress:
  - from:
    - podSelector:
        matchLabels:
                app: {{ template "drupal.fullname" . }}-mariadb-slave
{{- end }}
