kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ template "drupal.fullname" . }}-calico
spec:
  podSelector:
    matchLabels:
      app: {{ template "drupal.fullname" . }}-mariadb-master
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: {{ template "drupal.fullname" . }}-drupal
