---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "drupal.fullname" . }}-mariadb
  labels:
    app: {{ template "drupal.fullname" . }}-mariadb-master
    chart: mariadb-5.0.4
    release: "{{ template "drupal.fullname" . }}"
    heritage: "Tiller"
type: Opaque
data:

  mariadb-root-password: "{{ .Values.db.rootUser.password | b64enc }}"
  mariadb-password: "{{ .Values.db.password | b64enc }}"
  mariadb-replication-password: "{{ .Values.db.replication.password | b64enc }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "drupal.fullname" . }}-drupal
  labels:
    app: {{ template "drupal.fullname" . }}-drupal
    chart: drupal-2.1.0
    release: "{{ template "drupal.fullname" . }}"
    heritage: "Tiller"
type: Opaque
data:

  drupal-password: "{{ .Values.drupalPassword | b64enc }}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "drupal.fullname" . }}-mariadb-master-init-scripts
  labels:
    app: {{ template "drupal.fullname" . }}-mariadb-master
    component: "master"
    chart: mariadb-5.0.4
    release: "{{ template "drupal.fullname" . }}"
    heritage: "Tiller"
data:
  README.md: |-
    You can copy here your custom .sh, .sql or .sql.gz file so they are executed during the first boot of the image.

    More info in the [bitnami-docker-mariadb](https://github.com/bitnami/bitnami-docker-mariadb#initializing-a-new-instance) repository.
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "drupal.fullname" . }}-mariadb-master
  labels:
    app: {{ template "drupal.fullname" . }}-mariadb-master
    component: "master"
    chart: mariadb-5.0.4
    release: "{{ template "drupal.fullname" . }}"
    heritage: "Tiller"
data:
  my.cnf: |-
    [mysqld]
    skip-name-resolve
    explicit_defaults_for_timestamp
    basedir=/opt/bitnami/mariadb
    port=3306
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    tmpdir=/opt/bitnami/mariadb/tmp
    max_allowed_packet=16M
    bind-address=0.0.0.0
    pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
    log-error=/opt/bitnami/mariadb/logs/mysqld.log
    character-set-server=UTF8
    collation-server=utf8_general_ci

    [client]
    port=3306
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    default-character-set=UTF8

    [manager]
    port=3306
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "drupal.fullname" . }}-mariadb-slave
  labels:
    app: {{ template "drupal.fullname" . }}-mariadb-slave
    component: "slave"
    chart: mariadb-5.0.4
    release: "{{ template "drupal.fullname" . }}"
    heritage: "Tiller"
data:
  my.cnf: |-
    [mysqld]
    skip-name-resolve
    explicit_defaults_for_timestamp
    basedir=/opt/bitnami/mariadb
    port=3306
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    tmpdir=/opt/bitnami/mariadb/tmp
    max_allowed_packet=16M
    bind-address=0.0.0.0
    pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
    log-error=/opt/bitnami/mariadb/logs/mysqld.log
    character-set-server=UTF8
    collation-server=utf8_general_ci

    [client]
    port=3306
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    default-character-set=UTF8

    [manager]
    port=3306
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "drupal.fullname" . }}-mariadb-tests
data:
  run.sh: |-
    @test "Testing MariaDB is accessible" {
      mysql -h {{ template "drupal.fullname" . }}-mariadb -uroot -p$MARIADB_ROOT_PASSWORD -e 'show databases;'
    }
