---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "drupal.fullname" . }}-drupal
  labels:
    app: {{ template "drupal.fullname" . }}-drupal
    chart: drupal-2.1.0
    release: "{{ template "drupal.fullname" . }}"
    heritage: "Tiller"
spec:
  selector:
    matchLabels:
      app: {{ template "drupal.fullname" . }}-drupal
      release: "{{ template "drupal.fullname" . }}"
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "drupal.fullname" . }}-drupal
        chart: drupal-2.1.0
        release: "{{ template "drupal.fullname" . }}"
    spec:
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecrets  }}
      {{- end }}
      containers:
      - name: {{ template "drupal.fullname" . }}-drupal
        image: "{{ .Values.image.registry }}/{{ .Values.image.drupalrepository }}:{{ .Values.image.drupaltag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        - name: MARIADB_HOST
          value: {{ template "drupal.fullname" . }}-mariadb-master
        - name: MARIADB_PORT_NUMBER
          value: "3306"
        - name: DRUPAL_DATABASE_NAME
          value: "{{- printf "%s-%s" .Values.db.name .Release.Name | trunc 63 | trimSuffix "-" -}}"
        - name: DRUPAL_DATABASE_USER
          value: "{{ .Values.db.user }}"
        - name: DRUPAL_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "drupal.fullname" . }}-mariadb
              key: mariadb-password
        - name: DRUPAL_PROFILE
          value: "standard"
        - name: DRUPAL_USERNAME
          value: "{{ .Values.drupalUsername }}"
        - name: DRUPAL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "drupal.fullname" . }}-drupal
              key: drupal-password
        - name: DRUPAL_EMAIL
          value: "{{ .Values.drupalEmail }}"
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        livenessProbe:
          httpGet:
            path: /user/login
            port: http
          initialDelaySeconds: 240

        readinessProbe:
          httpGet:
            path: /user/login
            port: http
          initialDelaySeconds: 300

        resources:
          requests:
            cpu: 300m
            memory: 512Mi

        volumeMounts:
        - name: drupal-data
          mountPath: /bitnami/drupal
        - name: apache-data
          mountPath: /bitnami/apache
      volumes:
{{- if .Values.persistence.enabled -}}
      - name: drupal-data
        persistentVolumeClaim:
          claimName: {{ template "drupal.fullname" . }}-drupal-drupal
      - name: apache-data
        persistentVolumeClaim:
          claimName: {{ template "drupal.fullname" . }}-drupal-apache
{{- else }}
      - name: drupal-data
        emptyDir: {}
      - name: apache-data
        emptyDir: {}
{{- end }}
---
apiVersion: v1
kind: Pod
metadata:
  name: "{{ template "drupal.fullname" . }}-mariadb-test-aovqc"
  annotations:
    "helm.sh/hook": test-success
spec:
  initContainers:
    - name: "test-framework"
      image: "dduportal/bats:0.4.0"
      command:
        - "bash"
        - "-c"
        - |
          set -ex
          # copy bats to tools dir
          cp -R /usr/local/libexec/ /tools/bats/
      volumeMounts:
      - mountPath: /tools
        name: tools
  {{- if .Values.image.pullSecrets }}
  imagePullSecrets:
    - name: {{ .Values.image.pullSecrets  }}
  {{- end }}
  containers:
    - name: mariadb-test
      image: "{{ .Values.image.registry }}/{{ .Values.image.dbrepository }}:{{ .Values.image.dbtag }}"
      imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
      command: ["/tools/bats/bats", "-t", "/tests/run.sh"]
      env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "drupal.fullname" . }}-mariadb
              key: mariadb-root-password
      volumeMounts:
      - mountPath: /tests
        name: tests
        readOnly: true
      - mountPath: /tools
        name: tools
  volumes:
  - name: tests
    configMap:
      name: {{ template "drupal.fullname" . }}-mariadb-tests
  - name: tools
    emptyDir: {}
  restartPolicy: Never
